### ISSUE TITLE
Getting deprecation warning with Webpack 4.x

### ISSUE THREAD

**Issue by DGulshan** [nwinch/webpack-dotenv-plugin#22]
Hi,

I upgraded to webpack 4.5 & now I am getting a warning. Stack trace:

```
(node:70521) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
    at DotenvPlugin.apply (/Users/admin/my-project/node_modules/webpack-dotenv-plugin/index.js:40:12)
    at webpack (/Users/admin/my-project/node_modules/webpack/lib/webpack.js:37:12)
    at processOptions (/Users/admin/my-project/node_modules/webpack-cli/bin/webpack.js:436:16)
    at yargs.parse (/Users/admin/my-project/node_modules/webpack-cli/bin/webpack.js:512:3)
    at Object.parse (/Users/admin/my-project/node_modules/webpack-cli/node_modules/yargs/yargs.js:552:18)
    at /Users/admin/my-project/node_modules/webpack-cli/bin/webpack.js:217:8
    at Object.<anonymous> (/Users/admin/my-project/node_modules/webpack-cli/bin/webpack.js:514:3)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/admin/my-project/node_modules/webpack/bin/webpack.js:80:2)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
```

node: 8.6.0
webpack: 4.5.0
webpack-dotenv-plugin: 2.0.2

**Comment by DGulshan** [comment]
I've created a pull request with the fix: #23

**Comment by nwinch** [comment]
@DGulshan Thank you! Will merge this in a bit.

**Comment by DGulshan** [comment]
Hi @nwinch,
any updates on this?

**Comment by Amandeepsinghghai** [comment]
@nwinch First of all thanks for the package. It is really helpful. 
Just wanted to know if there are any updates on this PR?
